### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by RyDroid** [creationix/git-browser#12]
Hi.
This program is apparently under "MIT" license. https://github.com/creationix/git-browser/blob/master/package.json
However, there is no license file.
Moreover, "MIT license" is ambiguous. (X11) "This license is sometimes called the MIT license, but that term is misleading, since MIT has used many licenses for software." (Expat) "It is sometimes ambiguously referred to as the MIT License." https://www.gnu.org/licenses/license-list.html
Regards.

**Comment by creationix** [comment]
I included full license text.  That should resolve any questions.

**Comment by ghost** [comment]
Thanks.
